// <auto-generated />
using System;
using System.Text.Json;
using Hive.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hive.Infrastructure.Data.Migrations
{
    [DbContext(typeof(HiveDbContext))]
    partial class HiveDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hive.Domain.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Boot")
                        .HasColumnType("integer")
                        .HasColumnName("boot");

                    b.Property<JsonDocument>("Config")
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<int?>("ConfigAppliedRev")
                        .HasColumnType("integer")
                        .HasColumnName("config_applied_rev");

                    b.Property<int>("ConfigRev")
                        .HasColumnType("integer")
                        .HasColumnName("config_rev");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("device_id");

                    b.Property<string>("FwVersion")
                        .HasColumnType("text")
                        .HasColumnName("fw_version");

                    b.Property<string>("Hw")
                        .HasColumnType("text")
                        .HasColumnName("hw");

                    b.Property<JsonDocument>("Info")
                        .HasColumnType("jsonb")
                        .HasColumnName("info");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Mac")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("mac");

                    b.Property<string>("MqttUser")
                        .HasColumnType("text")
                        .HasColumnName("mqtt_user");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("Rssi")
                        .HasColumnType("integer")
                        .HasColumnName("rssi");

                    b.Property<JsonDocument>("State")
                        .HasColumnType("jsonb")
                        .HasColumnName("state");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type_code");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_device_id");

                    b.HasIndex("TypeCode")
                        .HasDatabaseName("ix_devices_type_code");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("ix_devices_zone_id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("Hive.Domain.DeviceEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<string>("AcknowledgedBy")
                        .HasColumnType("text")
                        .HasColumnName("acknowledged_by");

                    b.Property<bool?>("Armed")
                        .HasColumnType("boolean")
                        .HasColumnName("armed");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("device_id");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.Property<DateTimeOffset>("Ts")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<string>("ViaNode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("via_node");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("Ts")
                        .HasDatabaseName("ix_events_ts");

                    b.HasIndex("DeviceId", "Ts")
                        .HasDatabaseName("ix_events_device_id_ts");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Hive.Domain.DeviceHealth", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("ClockSkew")
                        .HasColumnType("boolean")
                        .HasColumnName("clock_skew");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("device_id");

                    b.Property<long>("HeapFree")
                        .HasColumnType("bigint")
                        .HasColumnName("heap_free");

                    b.Property<string>("ResetReason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reset_reason");

                    b.Property<int>("Rssi")
                        .HasColumnType("integer")
                        .HasColumnName("rssi");

                    b.Property<DateTimeOffset>("Ts")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts");

                    b.Property<long>("UptimeS")
                        .HasColumnType("bigint")
                        .HasColumnName("uptime_s");

                    b.Property<double?>("Vbat")
                        .HasColumnType("double precision")
                        .HasColumnName("vbat");

                    b.HasKey("Id")
                        .HasName("pk_device_health");

                    b.HasIndex("DeviceId", "Ts")
                        .HasDatabaseName("ix_device_health_device_id_ts");

                    b.ToTable("device_health", (string)null);
                });

            modelBuilder.Entity("Hive.Domain.DeviceLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<JsonDocument>("Ctx")
                        .HasColumnType("jsonb")
                        .HasColumnName("ctx");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("device_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("level");

                    b.Property<string>("Msg")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("msg");

                    b.Property<DateTimeOffset>("Ts")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts");

                    b.HasKey("Id")
                        .HasName("pk_device_logs");

                    b.HasIndex("DeviceId", "Ts")
                        .HasDatabaseName("ix_device_logs_device_id_ts");

                    b.ToTable("device_logs", (string)null);
                });

            modelBuilder.Entity("Hive.Domain.DeviceType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<JsonDocument>("Caps")
                        .HasColumnType("jsonb")
                        .HasColumnName("caps");

                    b.Property<JsonDocument>("DefaultConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("default_config");

                    b.Property<int>("OfflineAfterS")
                        .HasColumnType("integer")
                        .HasColumnName("offline_after_s");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("title");

                    b.HasKey("Code")
                        .HasName("pk_device_types");

                    b.ToTable("device_types", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "guard-cam",
                            OfflineAfterS = 180,
                            Title = "Камера с датчиком движения"
                        },
                        new
                        {
                            Code = "meteo",
                            OfflineAfterS = 180,
                            Title = "Метеодатчик"
                        },
                        new
                        {
                            Code = "heat",
                            OfflineAfterS = 180,
                            Title = "Обогрев"
                        },
                        new
                        {
                            Code = "leak",
                            OfflineAfterS = 180,
                            Title = "Датчик протечки с краном"
                        },
                        new
                        {
                            Code = "plant",
                            OfflineAfterS = 600,
                            Title = "Растения"
                        });
                });

            modelBuilder.Entity("Hive.Domain.TelemetryPoint", b =>
                {
                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metric");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<DateTimeOffset>("Ts")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.ToTable("telemetry", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Hive.Domain.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_zones");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("Hive.Domain.Device", b =>
                {
                    b.HasOne("Hive.Domain.DeviceType", null)
                        .WithMany()
                        .HasForeignKey("TypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_devices_device_types_type_code");

                    b.HasOne("Hive.Domain.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_devices_zones_zone_id");

                    b.Navigation("Zone");
                });
#pragma warning restore 612, 618
        }
    }
}
