<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Hive.Infrastructure/Hive.Infrastructure.csproj" />
    <ProjectReference Include="../Hive.Modules.Devices/Hive.Modules.Devices.csproj" />
    <ProjectReference Include="../Hive.Modules.Telemetry/Hive.Modules.Telemetry.csproj" />
    <ProjectReference Include="../Hive.Modules.Events/Hive.Modules.Events.csproj" />
    <ProjectReference Include="../Hive.Modules.Media/Hive.Modules.Media.csproj" />
    <ProjectReference Include="../Hive.Modules.Rules/Hive.Modules.Rules.csproj" />
    <ProjectReference Include="../Hive.Modules.Notify/Hive.Modules.Notify.csproj" />
    <ProjectReference Include="../Hive.Modules.Cluster/Hive.Modules.Cluster.csproj" />
    <ProjectReference Include="../Hive.Modules.Users/Hive.Modules.Users.csproj" />
  </ItemGroup>
</Project>
