<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Telegram.Bot" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Hive.Domain/Hive.Domain.csproj" />
    <ProjectReference Include="../Hive.Infrastructure/Hive.Infrastructure.csproj" />
    <ProjectReference Include="../Hive.Modules.Devices/Hive.Modules.Devices.csproj" />
    <ProjectReference Include="../Hive.Modules.Events/Hive.Modules.Events.csproj" />
    <ProjectReference Include="../Hive.Modules.Media/Hive.Modules.Media.csproj" />
    <ProjectReference Include="../Hive.Modules.Telemetry/Hive.Modules.Telemetry.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Hive.Tests.Integration" />
  </ItemGroup>
</Project>
